### ISSUE TITLE
Allow World to have a variable number of Systematics Managers

### ISSUE THREAD

**Issue by mercere99** [devosoft/Empirical#107]
As of now, the emp::World template (in evo3/) has a single Systematics member that tracks the organism's genotype.  Ideally, we should be able to have any number of systematics managers in a world that can track different aspects of the evolving population.  Each should take a function that converts an organism and its position into the thing to be tracked.

What might we want to track:
* Genotypes (as we are now) that group related organisms that have identical underlying genomes, and maintain their evolutionary history.
* Grid Positions: track how evolutionary lineages proceeded through space.
* Phenotypic Traits: Track the evolutionary history grouped by phenotypes rather than genotypes, allowing for more compressed trees.
* Individual Organisms: Sometimes we might not want to group two organisms just because they had the same genotype; this setup would allow us to store more information about every organism.
* Nothing: We should be able to have NO Systematics managers on, presumably speeding up a run and certainly decreasing the memory footprint.

**Comment by emilydolson** [comment]
Oops, should have closed this one when #166 was merged
