### ISSUE TITLE
Create a macro: emp_always_assert

### ISSUE THREAD

**Issue by mercere99** [devosoft/Empirical#110]
This macro should be identical to emp_assert, but still work outside of debug mode.

The goal is to be able to build debug tooling that can be used while the rest of the code is optimized.  For example, EMP_TRACK_MEM should be usable in conjunction with NDEBUG.

**Comment by emilydolson** [comment]
Added in #405, so I'm going to close this and open a new issue about swapping it into Ptr.H.
