### ISSUE TITLE
Mutations do not interact will with lineage tracking and synchronous generations

### ISSUE THREAD

**Issue by mercere99** [devosoft/Empirical#118]
Right now, when in "EA mode" a population will run through its selection mechanisms to create the next generation.  DoMutations() is then run on the population before making it active.  The EA part of this works fine.  HOWEVER an organism is placed in the lineage tracker when it is BORN, but this is technically before mutations are applied.

Ideally, all mutations should occur on birth (via a signal?), but we have to make sure things like elite selection can still turn off mutations.

Should be fixed before release!

**Comment by emilydolson** [comment]
Did we figure out a solution to this problem?

The best solution that I (while talking to Alex) have come up is to have the world call the mutation function in DoBirth. We can provide an additional function that you can use to tell the world which locations mutate. By default, all positions mutate.

Does that sound reasonable?

**Comment by emilydolson** [comment]
For those keeping track at home, preliminary fix is here: https://github.com/emilydolson/Empirical/tree/alife2018

**Comment by mercere99** [comment]
SetAutoMutate() should solve this problem.  It triggers mutations right before organisms are born, so they are properly placed in the systematics tracker.  If you include an optional function as an argument, the function will be given the position where the offspring is about to be placed and must return a true/false as to whether it should be mutated.
