### ISSUE TITLE
evo/World.h does not compile on gcc

### ISSUE THREAD

**Issue by grenewode** [devosoft/Empirical#123]
When a simple example file such as
```c++
#include "Evo/World.h"
int main() {}
```
is compiled with gcc, it gives the following error:

```
In file included from ../source/Evo/../control/Signal.h:23:0,
                 from ../source/Evo/World.h:31,
                 from main.cpp:1:
../source/Evo/../control/../tools/map_utils.h: In instantiation of ‘auto emp::Find(const MAP_T&, const KEY_T&, const DEFAULT_T&) [with MAP_T = std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >; KEY_T = std::__cxx11::basic_string<char>; DEFAULT_T = char [8]]’:
../source/Evo/World.h:429:46:   required from here
../source/Evo/../control/../tools/map_utils.h:32:20: error: inconsistent deduction for auto return type: ‘const char*’ and then ‘std::__cxx11::basic_string<char>’
     return val_it->second;
                    ^~~~~~
../source/Evo/../control/../tools/map_utils.h:32:20: error: cannot convert ‘std::__cxx11::basic_string<char>(val_it.std::_Rb_tree_const_iterator<std::pair<const std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >::operator->()->std::pair<const std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >::second)’ from type ‘std::__cxx11::basic_string<char>’ to type ‘const char*’
```

**Comment by grenewode** [comment]
I think this can be resolved by changing 
```c++
  template <class MAP_T, class KEY_T, class DEFAULT_T>
  inline auto Find( const MAP_T & in_map, const KEY_T & key, const DEFAULT_T & dval) {
    auto val_it = in_map.find(key);
    if (val_it == in_map.end()) return dval;
    return val_it->second;
  }
```
to
```c++
  template <class MAP_T, class KEY_T, class DEFAULT_T = MAP_T::mapped_type>
  inline auto Find( const MAP_T & in_map, const KEY_T & key, const DEFAULT_T & dval) {
    auto val_it = in_map.find(key);
    if (val_it == in_map.end()) return dval;
    return val_it->second;
  }
```
which allows gcc to do the deduction, (I think) because now it converts `cost char*` to `const std::string&` when it is passed as an argument to `Find` instead of doing deduction at return time. However, I am also wondering if would ever be a case when `DEFAULT_T` is not going to be exactly `MAP_T::mapped_type`, in which case it might be better to just use
```c++
  template <class MAP_T, class KEY_T>
  inline auto Find( const MAP_T & in_map, const KEY_T & key, const MAP_T::mapped_type & dval) {
    auto val_it = in_map.find(key);
    if (val_it == in_map.end()) return dval;
    return val_it->second;
  }
```

**Comment by mercere99** [comment]
I'm not able to duplicate the error using GCC 7.1.0.  Which version are you using?

**Comment by mercere99** [comment]
(That said, I don't object to having default template arguments if it promotes backward compatibility.)

**Comment by grenewode** [comment]
So this is very interesting. I have gcc 7.2.0. Maybe clang is wrong?

**Comment by mercere99** [comment]
I wouldn't be surprised if they fixed some subtle ambiguity in GCC (where they were technically making an "obvious" assumption that couldn't be guaranteed) and clang hasn't fixed it yet.  I'd say go ahead and push the fix, unless you'd prefer I do it.

**Comment by grenewode** [comment]
I should be able to. Do you have a process for pull requests? Also, any thoughts on using the first solution vs the second?

**Comment by mercere99** [comment]
Ah, I see the issue.  I think the second version is all around safer, since it guarantees that we're always dealing with the mapped type, which we should be.

**Comment by mercere99** [comment]
BTW, this simplification of Find (which used to have a version for each type of map) is pretty recent, so I'm not surprised the problem hasn't come up before.

**Comment by mercere99** [comment]
As for pull requests, I don't think we've settled on a system, though we probably should.  I'll ping @bocajnotnef since I know he laid out some ideas.  For now, just set it up and I'll test and approve it.

**Comment by grenewode** [comment]
While I'm at it, should I fix the FindRef function? I think it has the same problem.

**Comment by mercere99** [comment]
Please do!  (And generally, I'm quite happy with any fixes like that.)
