### ISSUE TITLE
Feature request: Config objects generate settings dashboards for the web

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#132]
Usually, when you make a web GUI for an experiment, it would be nice to be able to change all of the settings from the website. Creating input options for all of them is a bit of a pain, but seems like it should be possible to automate. The one tricky thing is deciding which input format (text box? drop down? slider?) to use for each setting. An easy first pass would be to have everything default to text boxes and make it possible to specify if necessary.

I think this could be good low-hanging fruit (although it does require understanding how configs get built, which is a little tricky), and don't have time to do it right now, so I'm putting it here as a reminder.

**Comment by mercere99** [comment]
See issue #33 

But yes -- this is critical!

**Comment by emilydolson** [comment]
Darn it, I guess I didn't go back far enough when looking for duplicates.

**Comment by mercere99** [comment]
Some good points here though -- for example, I hadn't considered that this could be made low-hanging fruit merely by making everything a textbox.
