### ISSUE TITLE
Histogram buckets not working

### ISSUE THREAD

**Issue by anyaevostinar** [devosoft/Empirical#137]
When I set up a histogram data node as SetupBins(-1.0, 1.0, 20), it is putting values of 0.5 into the -0.5 bucket and -0.5 into the 0.7 bucket. I tried putting `bins.Adjust(emp::vector<double>(num_bins, width));` into my Empirical/source/data/DataNode.h file's SetupBins. That makes the widths say they are 0.1 (as opposed to the width of 10 they were without that hack), but nothing going in the correct bucket still.

**Comment by emilydolson** [comment]
Fixed in b0e2f71ddbef3ef2c1b9bf008741710cbfdcebcc (although to_string got broken in the process)

**Comment by mercere99** [comment]
The frustrating part is that to_string is NOT broken on my machine.  *Grumble*

I think I know what's wrong, though, and will get if fixed asap.
