### ISSUE TITLE
emp::Ptr behavior not identical to native pointer behavior in debug mode

### ISSUE THREAD

**Issue by mmore500** [devosoft/Empirical#155]
Here are code snippets that work as they should in debug mode:
```
  // current signal state
  GridStack<int>* signal;
  // next signal state
  GridStack<int>* sigbuff;
 
...
	
    // swap buffer in
    GridStack<int>* temp = sigbuff;
    sigbuff = signal;
    signal = temp;
```

```
 // current signal state
  emp::Ptr<GridStack<int>> signal;
  // next signal state
  emp::Ptr<GridStack<int>> sigbuff;

...
...
	
	 // swap buffer in
    std::swap(signal, sigbuff);
```
```
  // current signal state
  emp::Ptr<GridStack<int>> signal;
  // next signal state
  emp::Ptr<GridStack<int>> sigbuff;

...
...
	    // swap buffer in
    GridStack<int>* temp = sigbuff;
    sigbuff = signal;
    signal = temp;
    temp = nullptr;

```

Here are snippets that don't work as they should in debug mode:
```
 // current signal state
  emp::Ptr<GridStack<int>> signal;
  // next signal state
  emp::Ptr<GridStack<int>> sigbuff;

...
...
	
	    // swap buffer in
    emp::Ptr<GridStack<int>> temp = sigbuff;
    sigbuff = signal;
    signal = temp;
    temp = nullptr;
```

```
  // current signal state
  emp::Ptr<GridStack<int>> signal;
  // next signal state
  emp::Ptr<GridStack<int>> sigbuff;

...
	
	    // swap buffer in
    emp::Ptr<GridStack<int>> temp = sigbuff;
    sigbuff = signal;
    signal = temp;
```

**Comment by mercere99** [comment]
How do the signal and sigbuff pointers get set in your code (before they are swapped)?

**Comment by mercere99** [comment]
I've tried a few more things and can't seem to replicate the bug.  :(

**Comment by mmore500** [comment]
Here's where the pointers are initialized...

```
public:
  SignalManager(
    DishtinyConfig& dconfig,
    GridSpec& spec)
    : ACTIVATED(-1)
    , READY(0)
    , QUIESCENT_MAX(dconfig.QUIESCENT_MAX())
    , NLEV(dconfig.NLEV())
    , signal(new GridStack<int>(READY, spec, dconfig.NLEV()))
    , sigbuff(new GridStack<int>(READY, spec, dconfig.NLEV()))
    { ; }
```

**Comment by mmore500** [comment]
Here's a link with the complete context:
https://github.com/mmore500/dishtiny/tree/2418c96e3a5ac83256c4038a25067cb479d379cc

**Comment by mercere99** [comment]
When using Ptr, try changing `new GridStack<int>(READY, spec, dconfig.NLEV())` to `emp::NewPtr<GridStack<int>>(READY, spec, dconfig.NLEV())`

Ptr will not perform as many checks on pointers that were created on the outside and then passed in; if you create it as a Ptr it will warn you of any problems going on (such as not deleting it or using it after it was deleted)

Likewise, when you finally delete it, do `signal.Delete()` (for signal)

**Comment by mmore500** [comment]
Should I make those changes and see if the bug is occurs under those conditions?

**Comment by mercere99** [comment]
If you can.  It won't fix the bug, but it may help to diagnose it.

**Comment by mmore500** [comment]
Will do.

**Comment by mmore500** [comment]
Looks like everything works as it should in debug mode with 

```
class SignalManager {
private:
  const int ACTIVATED;
  const int READY;
  const int QUIESCENT_MAX;

  const size_t NLEV;

  // current signal state
  emp::Ptr<GridStack<int>> signal;
  // next signal state
  emp::Ptr<GridStack<int>> sigbuff;

public:
  SignalManager(
    DishtinyConfig& dconfig,
    GridSpec& spec)
    : ACTIVATED(-1)
    , READY(0)
    , QUIESCENT_MAX(dconfig.QUIESCENT_MAX())
    , NLEV(dconfig.NLEV())
    , signal(emp::NewPtr<GridStack<int>>(READY, spec, dconfig.NLEV()))
    , sigbuff(emp::NewPtr<GridStack<int>>(READY, spec, dconfig.NLEV()))
    { ; }

...
...

    // swap buffer in
    emp::Ptr<GridStack<int>> temp = sigbuff;
    sigbuff = signal;
    signal = temp;
```

**Comment by mercere99** [comment]
So -- the problem DID go away by switching to NewPtr and Delete?  How odd...  Well, that certainly gives me a big hint as to the problem.

At the end of the run in debug mode, did it print one final line about the status of the pointers?

**Comment by mmore500** [comment]
It crashes before the end of the run. I can do a shorter run to try to look at that before it crashes. Which code variant of the above should I run it with?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Charles OfriaSent: Thursday, March 22, 2018 4:21 PMTo: devosoft/EmpiricalReply To: devosoft/EmpiricalCc: Matthew Moreno; AuthorSubject: Re: [devosoft/Empirical] emp::Ptr behavior not identical to native pointer behavior in debug mode (#155)So -- the problem DID go away by switching to NewPtr and Delete?  How odd...  Well, that certainly gives me a big hint as to the problem.
At the end of the run in debug mode, did it print one final line about the status of the pointers?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/devosoft/Empirical","title":"devosoft/Empirical","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/devosoft/Empirical"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mercere99 in #155: So -- the problem DID go away by switching to NewPtr and Delete?  How odd...  Well, that certainly gives me a big hint as to the problem.\r\n\r\nAt the end of the run in debug mode, did it print one final line about the status of the pointers?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/devosoft/Empirical/issues/155#issuecomment-375444193"}}}

**Comment by mercere99** [comment]
Use the variant that WAS crashing (with emp::Ptr<> and a manual swap using a temporary pointer, all in debug mode), but with the addition of the NewPtr() and Delete() functions.

That will track what happens to the pointers all the way through the run and then print out details when the run ends (or errors, such as certain memory being lost or not deleted properly).

**Comment by mmore500** [comment]
In this context
```
  // current signal state
  emp::Ptr<GridStack<int>> signal;
  // next signal state
  emp::Ptr<GridStack<int>> sigbuff;

public:
  SignalManager(
    DishtinyConfig& dconfig,
    GridSpec& spec)
    : ACTIVATED(-1)
    , READY(0)
    , QUIESCENT_MAX(dconfig.QUIESCENT_MAX())
    , NLEV(dconfig.NLEV())
    , signal(new GridStack<int>(READY, spec, dconfig.NLEV()))
    , sigbuff(new GridStack<int>(READY, spec, dconfig.NLEV()))
    { ; }
...
...
	    // swap buffer in
    emp::Ptr<GridStack<int>> temp = sigbuff;
    sigbuff = signal;
    signal = temp;
```

Here's my output where the run is short enough it stops before it crashes.
```
ERROR: Unable to open config file 'configs.cfg'. Ignoring.

==============================
|    How am I configured?    |
==============================
### DEFAULT ###
# Default settings for DISHTINY

set QUIESCENT_MAX 4         # Length of quiescent period
set NLEV 2                  # Number hierarchical resource lebels
set SEED 0                  # Random number seed (0 for based on time)
set GRID_H 120              # Height dimension of the grid
set GRID_W 120              # Width dimension of the grid
set MAX_GENS 2000           # How many generations should we process?

set REP_THRESH 8.000000     # How much should replication cost?
set KILL_THRESH -11.000000  # What is the minimum resource level required to stay alive?
set CH_MAX 4194304          # What is the maximum value of a channel identifier?
set CULL_FREQ 2500          # How frequently should culling take place?
set GDATA_FREQ 2000         # How frequently should we take genotype data?
set PDATA_FREQ 100          # How frequently should we take phenotype data?
set PUPDATE_FREQ 100        # How frequently should we print the current update?
set SUICIDE_EFF 0.800000    # How frequently should suicide attempts succeed?
set RUN_LENGTH 1000         # How many updates should we run the experiment for?

==============================

EMP_TRACK_MEM: Pointer tracking is active!
update 0
update 100
update 200
update 300
update 400
update 500
update 600
update 700
update 800
update 900
EMP_TRACK_MEM: No memory leaks found!
 32201 pointers found; 0 still exist with a non-null value (but have been properly deleted)
```

**Comment by mercere99** [comment]
This is the version that was failing, correct (and presumably still would be if you let it run longer).

What I actually need is the one where you DO change the new to NewPtr() and delete to Delete().

Sorry for the confusion!  It's good to see there are no other issues, so if that change does cause any, we know the source.

**Comment by mmore500** [comment]
In this context,
```
  // current signal state
  emp::Ptr<GridStack<int>> signal;
  // next signal state
  emp::Ptr<GridStack<int>> sigbuff;

public:
  SignalManager(
    DishtinyConfig& dconfig,
    GridSpec& spec)
    : ACTIVATED(-1)
    , READY(0)
    , QUIESCENT_MAX(dconfig.QUIESCENT_MAX())
    , NLEV(dconfig.NLEV())
    , signal(emp::NewPtr<GridStack<int>>(READY, spec, dconfig.NLEV()))
    , sigbuff(emp::NewPtr<GridStack<int>>(READY, spec, dconfig.NLEV()))
    { ; }

    ~SignalManager() {
      signal.Delete();
      sigbuff.Delete();
    }
...
    // swap buffer in
    emp::Ptr<GridStack<int>> temp = sigbuff;
    sigbuff = signal;
    signal = temp;
```
the program works as it should in debug mode and this is the printed output
```
ERROR: Unable to open config file 'configs.cfg'. Ignoring.

==============================
|    How am I configured?    |

==============================
### DEFAULT ###
# Default settings for DISHTINY

set QUIESCENT_MAX 4         # Length of quiescent period
set NLEV 2                  # Number hierarchical resource lebels
set SEED 0                  # Random number seed (0 for based on time)
set GRID_H 120              # Height dimension of the grid
set GRID_W 120              # Width dimension of the grid
set MAX_GENS 2000           # How many generations should we process?
set REP_THRESH 8.000000     # How much should replication cost?
set KILL_THRESH -11.000000  # What is the minimum resource level required to stay alive?
set CH_MAX 4194304          # What is the maximum value of a channel identifier?
set CULL_FREQ 2500          # How frequently should culling take place?
set GDATA_FREQ 2000         # How frequently should we take genotype data?
set PDATA_FREQ 100          # How frequently should we take phenotype data?
set PUPDATE_FREQ 100        # How frequently should we print the current update?
set SUICIDE_EFF 0.800000    # How frequently should suicide attempts succeed?
set RUN_LENGTH 1000         # How many updates should we run the experiment for?

==============================

EMP_TRACK_MEM: Pointer tracking is active!
update 0
update 100
update 200
update 300
update 400
update 500
update 600
update 700
update 800
update 900
EMP_TRACK_MEM: No memory leaks found!
 37349 pointers found; 0 still exist with a non-null value (but have been properly deleted)
```

**Comment by mmore500** [comment]
Exactly correct the code
```
  // current signal state
  emp::Ptr<GridStack<int>> signal;
  // next signal state
  emp::Ptr<GridStack<int>> sigbuff;

public:
  SignalManager(
    DishtinyConfig& dconfig,
    GridSpec& spec)
    : ACTIVATED(-1)
    , READY(0)
    , QUIESCENT_MAX(dconfig.QUIESCENT_MAX())
    , NLEV(dconfig.NLEV())
    , signal(new GridStack<int>(READY, spec, dconfig.NLEV()))
    , sigbuff(new GridStack<int>(READY, spec, dconfig.NLEV()))
    { ; }
...
...
	    // swap buffer in
    emp::Ptr<GridStack<int>> temp = sigbuff;
    sigbuff = signal;
    signal = temp;
```
doesn't work properly in debug mode and would lead to a crash if allowed to run long enough to kill the entire population.

**Comment by mmore500** [comment]
With code at ` 71162426268b6bfb91ba1a26fb92519c96dc6c6c`,  the code 
```
 // current signal state
  emp::Ptr<GridStack<int>> signal;
  // next signal state
  emp::Ptr<GridStack<int>> sigbuff;

public:
  SignalManager(
    DishtinyConfig& dconfig,
    GridSpec& spec)
    : ACTIVATED(-1)
    , READY(0)
    , QUIESCENT_MAX(dconfig.QUIESCENT_MAX())
    , NLEV(dconfig.NLEV())
    , signal(new GridStack<int>(READY, spec, dconfig.NLEV()))
    , sigbuff(new GridStack<int>(READY, spec, dconfig.NLEV()))
    { ; }
...
...
	    // swap buffer in
    emp::Ptr<GridStack<int>> temp = sigbuff;
    sigbuff = signal;
    signal = temp;
```
now works in debug mode.

**Comment by mmore500** [comment]
Thanks!
