### ISSUE TITLE
Systematics manager breaks if you turn off ancestor tracking

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#198]
Currently, the systematics manager keeps track of "total offspring" of each taxon (i.e. the total number of extant taxa that that taxon is the ancestor of). This is achieved with the following loop in the `MarkExtinct` method of the systematics manager:

```
    if (taxon->GetParent()) {
      // Update extant descendant count for all ancestors
      taxon->GetParent()->RemoveTotalOffspring();
    }
```

When we're tracking ancestors, this is all well and good. However, if we turn ancestor tracking off, this ends up dereferencing a null pointer because taxa do not get notified when their parents go extinct. I see two ways to fix this:

1. Don't try to track total offspring when we aren't tracking extinct ancestors.
2. Make the phylogeny doubly-linked instead of singly-linked (i.e. parents have pointers to all of their offspring in addition to offspring having pointers to their parents). That way, when a node goes extinct it could notify all of its offspring and they could set their parent to nullptr. This would be more powerful in the long run, and would be helpful for various functionality we might want to implement in the future. However, I imagine it would complicate the bookkeeping.

**Comment by emilydolson** [comment]
Anyone have opinions on this? (perhaps @mercere99?) I'm hoping to pull request in a chunk of systematics fixes soon and it would be good to include a solution to this.

Currently I'm kind of leaning towards doubly-linked phylogenies, because there are some metrics I'm currently trying to calculate that would be way easier if I could traverse from the top to bottom.

**Comment by mercere99** [comment]
I'm not worried about complicated bookkeeping -- if we solve that once, we should be fine, and I don't think it will be too bad to begin with.  I think memory impact should also not be too bad, at worst doubling the size of phylogenies (but presumably less than that).  That said, I know that when we do track full phylogenies we can run into memory issues.  It's tempting to turn on double-linked trees only when we are NOT keeping ancestors, but that creates much more of a complexity headache.

My instinct is to just make them all doubly linked and see how bad the memory hit is.

A secondary option is to keep parents around as long as they have extant children.  Our normal pruning algorithm has been to remove a node when all of its descendants have dies out, but we can go for a simpler approach of removing it when all of its immediate children have gone extinct regardless of whether they left any descendants.  I think that would solve your problem above, and may even be easier to implement than a double-linked tree...

**Comment by emilydolson** [comment]
It would just be adding a pointer to each node, right? Shouldn't it be way less than doubling the memory?

It seems like pruning when immediate children are extinct would break most phylogeny things we would want to do... I'll see how bad making it doubly linked is.

**Comment by emilydolson** [comment]
Still not 100% convinced I'm not missing something subtle, but I think the bookkeeping is actually trivially easy.

**Comment by mercere99** [comment]
I agree that I should be straightforward AND that it should typically be much less than doubling (how close it is depends on how much other info we record, no?)  I *do* think it should be the first thing tried, and only if it's either more complicated or much larger than either of us expect should we consider other options.

**Comment by emilydolson** [comment]
With the merging of #283, this is fixed!

**Comment by mercere99** [comment]
Sorry to have missed this conversation when it was happening, but I do fully agree with the solution.  It doubles the number of pointers (since every pointer now has a complement pointing back to it), but I suspect the pointers themselves are relatively small compared to the other information being stored, so much less than doubling of total memory.

There are some lazy tracking methods we could use (i.e., a single value indicating how many offspring know that the parent is ready for removal, and it only happening then), but that would be far more complicated for minimal savings.  If it turns out that systematic memory is a problem, we can always return to it.
