### ISSUE TITLE
Including web/init.h and compiling without Emscripten fails on static_assert in Initialize()

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#199]
I'm not sure why this is happening now and wasn't before.

**Comment by emilydolson** [comment]
The reason for this was the change made [here](https://github.com/devosoft/Empirical/commit/2b9a1d2ca99883f39dae4e9ac162732a8fedb238). The intention was to warn the user that they probably don't want to be compiling web code without Emscripten, since it won't do anything. This is a good warning most of the time, but there are scenarios where it is useful to be able to compile web code without Emscripten (e.g. if you want code that has a GUI when compiled to the web, but is still allowed to be compiled natively, using the stubs helpful supplied in init.h). Now that we have `emp_assert_warning`, I propose we replace this `static_assert` with a warning (and probably something better once #406 gets merged in). Any objections, @mercere99?

Another useful side effect of this change is that it would make my plan to get web test coverage working possible.

**Comment by mercere99** [comment]
Sounds like a good plan!

**Comment by emilydolson** [comment]
Fixed by #415
