### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by nahumj** [devosoft/Empirical#2]

**Comment by bocajnotnef** [comment]
+1 to CI, though I feel unit testing should come first.

**Comment by bocajnotnef** [comment]
Though, adding tests is a never ending process. I'd like to get catch integrated and have a way of metricing code coverage before getting a CI up.

**Comment by mercere99** [comment]
Sounds like a good plan.  I think the CI will be pretty straightforward in comparison to the testing framework as a whole, so it makes sense to do the testing first.

**Comment by bocajnotnef** [comment]
@mercere99 Looks like whoever does this will need admin access to the repository

**Comment by bocajnotnef** [comment]
@mercere99 Actually strike that, it looks like Travis is built to interface eiither with personal projects that one is the owner of (i.e. you, for Empirical) or with organizations via a user with admin authority.

Not sure if it supports integrating with a personal repo via someone that isn't the owner.

**Comment by mercere99** [comment]
Okay -- let me know what you need me to do to get things setup.

**Comment by bocajnotnef** [comment]
I believe if you follow the steps at https://travis-ci.org/getting_started I
can manipulate the yml config gile to do what I need--the travis admin page
isn't very extensive so I assume much of it can be configured within the
yml file.

(Might also be worth looking into transferring custody of Empirical to an
organization, but that's a discussion for another time, I think.)

**Comment by emilydolson** [comment]
Transferring it to the Devosoft organization might be a relatively easy solution.

**Comment by mercere99** [comment]
Transferring it to Devosoft should be a viable option.  I just sent Jake a member request and made Emily an owner of the organization (since I don't think I'm going to be able to look at this in more detail until some time next week at soonest)

**Comment by bocajnotnef** [comment]
Happening in #32 

CI is up and running and can be observed in #32 for now. Once it's merged it it should Just Work (tm) automatically on any push into the repo/PR. PR CI status is view able within the PR and all builds can be seen at https://travis-ci.org/devosoft/Empirical/builds

**Comment by bocajnotnef** [comment]
Closing #2, resolved by #32
