### ISSUE TITLE
Changelog idea: changelog dir

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#26]
filenames == PR #'s
makestarget to concatenate into official changelog

**Comment by bocajnotnef** [comment]
should be fairly easy to assemble a python (or bash) script.

**Comment by bocajnotnef** [comment]
being prototyped in #31

**Comment by bocajnotnef** [comment]
stale; will re-open if someone argues for it.

**Comment by mercere99** [comment]
Not sure if I'll argue per se, but I do frequently put in new features and we should come up with a way for everyone to know.  I've been sometimes posting in Empirical on Slack.  Changelog seems like it'll be more important when we make things public.
