### ISSUE TITLE
Seg-fault in asynchronous worlds when population goes extinct

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#268]
Any objections to changing this if condition:

https://github.com/devosoft/Empirical/blob/bdc6c74a28d47673192c28788c815711ae6a0604/source/Evolve/World.h#L1194

to `IsSynchronous()`?

Currently there's an issue where if you're using a synchronous world but the population fails to produce any offspring, this line causes `Update()` to act like it's suddenly an asynchronous world.

**Comment by mercere99** [comment]
Makes sense to me.

**Comment by emilydolson** [comment]
Fixed in #269
