### ISSUE TITLE
PR etiquette

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#27]
Couple different schools of thought on PRs
1. Open them immediately when you start working on an issue, so as other people can provide feedback/makes linking other issues etc. easier
2. Open them only when you're ready for merge

Arguably, 2 is more intuitive, though I prefer 1. 

@mercere99 discussed this and he pointed out that if we adopt 1 we'll have to make sure everyone adopts it, so incomplete PRs don't get merged by folk who missed the memo.

Thoughts/opinions?

**Comment by bocajnotnef** [comment]
Additionally, we could also use PR labels to indicate merge readiness (or lack thereof)

**Comment by emilydolson** [comment]
Seems like if we combine option #1 with labels, we get the best of both worlds. I'm definitely a fan of being able to see what everyone is working on.

**Comment by bocajnotnef** [comment]
+1 for labels and early PRs. Labels would make it easy to just sweep through open PRs and see what's blocked on review/questions/still under development.

**Comment by emilydolson** [comment]
I think we've now solidly incorporated labels + early PRs into our standard practice (although a lot of us, myself included, could probably still do better on the early PRs)
