### ISSUE TITLE
SignalGP SpawnCore In Constructor

### ISSUE THREAD

**Issue by mmore500** [devosoft/Empirical#270]
Empirical/hardware sgp spawns a core in one but not all of its constructors. e.g., [https://github.com/devosoft/Empirical/blob/c1889a6e2ccab392adbed687271a367cba893e0f/source/hardware/EventDrivenGP.h#L811](https://github.com/devosoft/Empirical/blob/c1889a6e2ccab392adbed687271a367cba893e0f/source/hardware/EventDrivenGP.h#L811)

The benefit of this is that new users don't have to worry about spawning a core. The downside of this is that it is potentially an unexpected gotcha, especially as it varies from constructor to constructor. I assume the user that doesn't want to have the spawned core should call `ResetHardware`? It seems odd to have the object initialized into a state different than where `ResetHardware` leaves it. 

I would suggest that we nix the SpawnCore, add a documenting comment somewhere that the user needs to do this themselves if they want it, and maybe carry over this change to new SignalGP? Thoughts @amlalejini ?

**Comment by amlalejini** [comment]
Yes (re: needing to call `ResetHardware`), yes (re: it seems odd...), and yes (re: nixing SpawnCore in constructor). 

I nixed in the new version of SignalGP, which is probably in a state where it's potentially worth porting a canonical version back into Empirical.
