### ISSUE TITLE
emp::Pow() slower and less precise than std::pow()

### ISSUE THREAD

**Issue by rodsan0** [devosoft/Empirical#279]
As per http://quick-bench.com/kytBRigyf6zM4FHPB5qqZXYiriI, it seems that emp::Pow() is slower than the standard library implementation when it's not constexpr. Moreover. the Variance test was recently failing because emp::Pow doesn't have full precision. 

@mmore500 and I propose that the emp::Variance implementation call std::pow under the hood. 

On C++20, there is a std::is_constant_evaluated that we could take advantage of inside emp::Pow to call std::pow if not in a constexpr context. Once the move to C++20 happens, this might be worth looking into further. It might be worth waiting on this issue until we can upgrade our codebase to C++20.

**Comment by mmore500** [comment]
this resource is probably worth looking at when we implement https://gist.github.com/Som1Lse/5309b114accc086d24b842fd803ba9d2
