### ISSUE TITLE
is_literal_string in string_utils.h doesn't accept escaped backslash

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#287]
For example, `emp::is_literal_string("\"\\Hello!\"")` returns false. Based on the code and comments, it looks like it should return true.

**Comment by mercere99** [comment]
I think the behavior is correct;  The above string, when all of the backslashes get processed becomes: "\Hello!"

\H is not allowed in a string literal, so I think it should be returning false.

If you want the literal string to be representing a backslash, you would need it to process to: "\\Hello!"

This would have required the original function to be `emp::is_literal_string("\"\\\\Hello!\"")`

**Comment by emilydolson** [comment]
Ah, okay that makes sense. Got confused on my backslash counting!
