### ISSUE TITLE
verify that absolute paths don't go boom

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#29]
currently I think diff-cover has a hardcoded path in its maketarget tht might break if people put their envs in other places

**Comment by bocajnotnef** [comment]
Does go boom, maketargets set up to prooduce these paths in an expected manner, see #32

**Comment by bocajnotnef** [comment]
diff-cover depreciated

**Comment by mercere99** [comment]
Should we try to figure out a replacement, of just let this die for now?
