### ISSUE TITLE
emp::unordered_map copy constructor issue while in debug mode

### ISSUE THREAD

**Issue by chavez-ju** [devosoft/Empirical#308]
After creating a copy constructor for a config (source/config/config.h) and using it for my project, I receive one of the following many errors:
```
../Empirical/source/config/config.h:412:17: error: object of type
      'emp::unordered_map<std::__2::basic_string<char>, emp::ConfigEntry *>'
      cannot be assigned because its copy assignment operator is implicitly
      deleted
        var_map = other.var_map;
```
From my understanding, I don't believe the copy constructor of an emp::unordered_map is working correctly (source/base/unordered_map.h)

**Comment by mercere99** [comment]
Thanks for catching this!  I fixed the constructors and believe that it should work now if you want to pull the newest version of Empirical.
