### ISSUE TITLE
Watch the Travis repo to see when they update cmake

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#36]
see #32, specifically https://github.com/devosoft/Empirical/pull/32#issuecomment-159052851

**Comment by emilydolson** [comment]
Looks like they're on cmake 3.2.2 now. Does that mean we can build docs on Travis now if we update stuff? Would that prevent the docs from constantly breaking?

**Comment by mercere99** [comment]
Is this now resolved?

**Comment by emilydolson** [comment]
Since we can now build the docs on Travis, I'm assuming yes?
