### ISSUE TITLE
Directory reorganization

### ISSUE THREAD

**Issue by amlalejini** [devosoft/Empirical#378]
As per discussion at several lab meetings, Empirical is due for a directory re-organization:

1. We will break up the source/tools directory because it is currently huge and unwieldy. 
2. We will rename the source directory to include to be more consistent with common practices by other C++ libraries. 
3. Everything in the `emp` namespace will be wrapped in an `emp` directory (e.g., include/emp/base/Ptr.h).

**Comment by amlalejini** [comment]
Proposed directory layout: https://trello.com/b/5VLwMYN2/empirical-tools-organization

**Comment by amlalejini** [comment]
Opened pull request #379 to address this issue.

**Comment by mmore500** [comment]
Per conversation with @mercere99  we should consider switching the file suffixes over to hpp and cpp as part of this change & get two birds with one stone

**Comment by amlalejini** [comment]
> Per conversation with @mercere99 we should consider switching the file suffixes over to hpp and cpp as part of this change & get two birds with one stone

Agreed. Are there tools that will automatically do the conversion (without having to write a bad python script)?

**Comment by mmore500** [comment]
Gnu rename comes to mind https://man7.org/linux/man-pages/man1/rename.1.html

**Comment by amlalejini** [comment]
The apps directory is wild y'all. Plugging the new apps discussion issue #382

**Comment by amlalejini** [comment]
Thing to discuss: what to do with wildly out of date examples (e.g., Empower)? Moving to examples/OLD directory for now (not a permanent solution).
