### ISSUE TITLE
OS X testing

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#39]
We technically support OS X but we don't currently have a way to test on it--I haven't even verified that our build process will work on a mac (e.g. all the make targets)

@mercere99 and I briefly discussed getting access to an OS X machine of Beacon's for Empirical (would need some graphical interfacing to get the initial dependencies installed--OS X security stuff needs graphical confirmation, which is annoying) but for most of the work simple shell access would be enough.

**Comment by bocajnotnef** [comment]
I'm counting the fact that @mercere99 develops on an os x machine as osx testing for now, unless someone gets cranky/a bug appears.

**Comment by mercere99** [comment]
Agreed -- I run all tests pretty regularly.  In the future we can get something more automated, but ignore it for now.
