### ISSUE TITLE
Where does config_web_interface.h belong?

### ISSUE THREAD

**Issue by amlalejini** [devosoft/Empirical#398]
Currently config_web_interface.hpp is located at source/config/config_web_interface.h. Should this file be in its current location or in the source/web directory? 

If someone attempts to compile it without emscripten, it triggers `static_assert(false, "Emscripten web tools require emcc for compilation (for now).");`

**Comment by mmore500** [comment]
I think it ends up as https://github.com/devosoft/Empirical/blob/fresh-prefab/source/prefab/ConfigPanel.h on the prefab ranch

**Comment by mmore500** [comment]
so we could just delete it here

**Comment by amlalejini** [comment]
Fantastic! Lets plan to remove it from config/ once the prefab PR is merged, then!
