### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com?

### ISSUE THREAD

**Issue by amlalejini** [devosoft/Empirical#400]
Looks like we're starting to bump up against the time limits on travis-ci.org or some of our tests (causing overall builds to fail). A couple of solutions off the top of my head (please comment with more ideas if you have some!):

- Migrate from travis-ci.org to travis-ci.com. Apparently the grass (server time) _is_ greener there. 
  - https://docs.travis-ci.com/user/migrate/open-source-repository-migration
- Try out GitHub Actions for CI testing
  - https://github.com/devosoft/Empirical/actions/new
  - https://docs.github.com/en/free-pro-team@latest/actions
- Reduce server time needed to run tests
  - I.e., break up each of the travis jobs so they finish under 50min

Of the above options, I _think_ the first one is the way to go.

**Comment by emilydolson** [comment]
Looks like we have successfully settled on option 2!
