### ISSUE TITLE
BitSet should have a 64-bit version for non-Emscripten efficiency

### ISSUE THREAD

**Issue by mercere99** [devosoft/Empirical#42]
emp::BitSet currently assumes 32-bit fields, which is what Emscripten uses, but most modern processes handle 64-bit value natively.

We've already made this shift with emp::BitVector, which gives something like a 20% speedup.  However if we ALWAYS use 64-bit values, we have a substantial slowdown in Emscripten since the 64-bit values need to be simulated.

It's definitely worth noting how this all works in BitVector and paralleling the changes.

**Comment by mmore500** [comment]
Done!
