### ISSUE TITLE
Add an .editorconfig file?

### ISSUE THREAD

**Issue by mmore500** [devosoft/Empirical#423]
**Is your feature request related to a problem? Please describe.**
@emilydolson recently went through a big headache having to manually reformat code a student had written because of whitespace issues.
We have a lot of different students working on this project, so maintaining consistency is really hard.

**Describe the solution you'd like**
We can add a .editorconfig file to the repository that matches our specifications and encourage students to install the editorconfig extension on their editor of choice.
Here's a link to the project page https://editorconfig.org/

It looks like it can even hook up to a GitHub action to enforce standards https://github.com/marketplace/actions/editorconfig-action

**Describe alternatives you've considered**
In the long term, we might look into using Clang format or a similar more powerful C++-specific tool but picking specs we like and getting students up and running with it would be a bit more of a push.

**Comment by emilydolson** [comment]
This looks great! I like how flexible it is. If I'm remembering correctly, part of the problem with clang format was that it handled embedded Javascript weird? So this seems like a good way around that.
