### ISSUE TITLE
ConfigPanel needs to be global variable currently

### ISSUE THREAD

**Issue by anyaevostinar** [devosoft/Empirical#428]
Currently the prefab configpanel needs to be a global variable, which is not obvious when implementing, so should either be changed or documented to avoid frustration

**Comment by emilydolson** [comment]
I'm pretty sure there's no way to change this (for the ConfigPanel or any other web object). Anything that isn't global is going to go out of scope fast unless a massive change is made to the way Emscripten generates Javascript.

I totally agree that we need to emphasize it more in the documentation. Currently it is mentioned a couple times in the web quickstart guide and that's it. As someone who recently had the experience of trying to debug this, what sort of documentation pages would you have looked at if they existed? e.g. if we had a "common gotchas when using Empirical" page, would you have looked there, or did this feel like it must be a ConfigPanel specific problem when you were debugging it?

Making a "common gotchas" page seems like pretty low-hanging fruit that would help with a lot of the most common problems. But maybe we should also be thinking about setting up a rule in doxygen that automatically puts a reminder about this on all web classes. That's less low-hanging fruit, but might be more effective.

**Comment by emilydolson** [comment]
Oh, or maybe I'm wrong. In #366 @kayakingCellist seemed to think it was possible to solve.

**Comment by anyaevostinar** [comment]
Would it work to declare the variable as an instance variable of an object that inherits from Animate? That was what I was going to do, and could still try, but you can't pass the config object to instantiate at that point, so best practice seems to suggest it being an instance variable and then instantiated in a constructor if that holding object is outside of main. 

I was going off the prefab example, so an inline comment in that example code would have saved me and generally both a common gotchas page and inline comments in the examples for these kinds of unintuitive things seems a good approach.

**Comment by lemniscate8** [comment]
From my testing the problem seems to be that all the callbacks for the inputs within the ConfigPanel capture `this`. But the component goes out of scope so that's a dangling reference and instead we should be capturing the shared pointer for this component. However, this will take some restructuring.
I'm planning an overhaul of this component in #436 to make it less monolithic and it should fix this bug, but let me know if there are any more features that would be nice (already got #427).
