### ISSUE TITLE
Cannot compile web examples

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#50]
Specifically Animate.js fails:

![image](https://cloud.githubusercontent.com/assets/2142082/11724569/d8219f5c-9f42-11e5-8def-a32719c6bd5a.png)

**Comment by bocajnotnef** [comment]
Table.js also fails, for the same reason.

**Comment by bocajnotnef** [comment]
We appear to be breaking on this line throughout the files:

`UI::Document doc("emp_base");`

**Comment by bocajnotnef** [comment]
@mercere99 Any insight?

**Comment by bocajnotnef** [comment]
Did some digging; the only backslashes that appear in the spewed output are to a call to .append. Grepping through the codebase that only happens in web/Slate.h and web/Table.h

Going to do some mucking around and see what else there is to see.

![image](https://cloud.githubusercontent.com/assets/2142082/11735433/26958594-9f8f-11e5-949e-779ddf625ebd.png)

**Comment by bocajnotnef** [comment]
HA! Got it!

Had to change `$('#' + parent_id).append('<span id=\'' + child_id + '\'></span>');` from using single quotes to double quotes in both `web/Table.h` and `web/Slate.h`, thus eliminating the need for an escape (and the builder yelling about the malformed escape) and thus the exploding build.

Fix is in 112ee1aefdc55584140323ca01cc5987dc65abfb, will make its way into master eventually.

This is a perfect example of why we need better test coverage. Gah.

**Comment by mercere99** [comment]
This seems like an odd problem -- I wonder if its a difference with the newer version of Emscripten.  Javascript allows both single or double quotes to be used interchangeably.  Emscripten, on the other hand, only guarantees that single quotes will work, because double quotes can screw up the macro (I think).  I'll play with it tomorrow and see if I can figure out what's going on.

**Comment by bocajnotnef** [comment]
ack, also:

![image](https://cloud.githubusercontent.com/assets/2142082/11735651/ca4d3040-9f91-11e5-9ae9-cb9e1d3941a3.png)

easy fix, but ew. 

Gonna add all web examples to the travis testing. Even if we don't run it we'll at least know it'll compile.

**Comment by bocajnotnef** [comment]
Oooh, that's looking for a member...

I'll stop libedebugging in an issue now.

**Comment by bocajnotnef** [comment]
New issue:

`./../../web/commands.h:27:11: error: no member named 'append_ok' in 'emp::web::internal::WidgetInfo' `

some commentary here: https://avida.slack.com/archives/dev-flood/p1449807686000012

Gonna shelve this for tonight and hammer on it during meeting with @mercere99

**Comment by bocajnotnef** [comment]
cannot reproduce as of `v0.0.1-133-g3bb0662`

**Comment by mercere99** [comment]
I think I fixed this a while back; I should have been paying more attention to issues.
