### ISSUE TITLE
Necessity of 'native' maketarget for web examples

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#54]
I'm working my way through the web examples file and I realized that the `native` maketarget falls over because of a bunch of JS/Emscripten specific material that g++/gcc tries to compile. 

Is it necessary to have a 'native' maketarget in a folder that relies specifically on using JS for the UI?

Additionally, I need to find a way to make Travis use Emscripten. I don't think there's a docker container for the EMSDK, which presents an issue. In theory we could clone in the SDK and build emcc from source, but that'll take a tremendously long time to compile for each build.

**Comment by mercere99** [comment]
The native make target doesn't work YET, but when I get a few more stubs in place it will.  There are just MUCH better debuggers for g++ than there are for Emscripten.

**Comment by bocajnotnef** [comment]
Alright, that makes sense.

Mostly I was working on a way to have Travis build the Web director to
prevent regression.

**Comment by emilydolson** [comment]
As of #415 native make targets work reliably and are clearly valuable :)
