### ISSUE TITLE
Run emscripten-based code within Travis

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#55]
Means we have to find an emscripten package/container for travis, and I don't think one currently exists.

Well, we can install the emscripten package from apt-get, but the version of that package might not play nice with our code.

**Comment by bocajnotnef** [comment]
TO-DO:

 - [ ] Attempt to compile emscripten code (e.g. `examples/web`) using apt-get emscripten

**Comment by mercere99** [comment]
Emscripten is notoriously problematic when installed through package management systems; I'm not sure why.  That said, it may be worth trying out to see if you can get it to work, but even so I'd worry a bit about maintenance.

**Comment by bocajnotnef** [comment]
Running `make` within `examples/web` spews loads of errors such as this:

![screenshot from 2015-12-26 14-36-40](https://cloud.githubusercontent.com/assets/2142082/12007698/2f7c56aa-abde-11e5-9651-e5c281a96665.png)

**Comment by IngwiePhoenix** [comment]
Any progress here? Recently made a package Emscripten aware and would like to run tests against that in CI.

**Comment by emilydolson** [comment]
This was solved (albeit imperfectly) in https://github.com/devosoft/Empirical/issues/93.
