### ISSUE TITLE
64bit / desktop bug with getting and setting bytes and Uints

### ISSUE THREAD

**Issue by JorySchossau** [devosoft/Empirical#57]
GetByte returns incorrect data when using a 64bit machine. Also, some other parts are hard-coded for 32-bit while others are made flexible with preprocessor `typedef uint32_t field_type` or `typedef uint64_t field_type`.

One way to reproduce:

```
BitVector bv(64); // 64 bits of data
bv.SetUInt(0,707406378); // sets first 32 bits to each byte=42 (should probably be renamed, or made flexible too)
bv.SetUInt(1,707406378); // sets second 32 bits to each byte=42
assert((int)bv.GetByte(0) == 42); // Pass
assert((int)bv.GetByte(1) == 42); // Pass
assert((int)bv.GetByte(2) == 42); // Pass
assert((int)bv.GetByte(3) == 42); // Pass
assert((int)bv.GetByte(4) == 42); // Fails
``
```

**Comment by emilydolson** [comment]
Was this fully solved by https://github.com/devosoft/Empirical/pull/58 and https://github.com/devosoft/Empirical/pull/59? If so, can we close this issue?

**Comment by mercere99** [comment]
Looks like it!
