### ISSUE TITLE
error: expression ‘(in_bool = (! in_bool))’ is not a constant-expression

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#61]
Looks like the fix for #60 (or one of the other two commits around then) introduced an error. When I try to compile examples/evo/NK.cc I get this error:

../../evo/../tools/functions.h: In function ‘constexpr bool emp::toggle(bool&)’:
../../evo/../tools/functions.h:37:79: error: expression ‘(in_bool = (! in_bool))’ is not a constant-expression
   inline constexpr bool toggle(bool & in_bool) { return (in_bool = !in_bool); }

**Comment by mercere99** [comment]
I'm having trouble duplicating the error (NK.cc is compiling fine for me).  As a quick fix, you should be able to remove the constexpr on line 37 of functions.h.  That is something I just added, but I don't see why it should be causing a problem.

Which compiler are you using?

**Comment by emilydolson** [comment]
g++, with --std=c++11

**Comment by mercere99** [comment]
Okay -- looks like a difference between C++11 implementation on clang and gcc.  I've removed the constexpr and it should work fine now.  When we migrate to C++14 the issue goes away.  (C++11 conflates const and constexpr in a way that gets fixed in C++14, and was already fixed in 11 on clang)
