### ISSUE TITLE
Little bugs in docs

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#71]
@bocajnotnef - here is the list of unimportant little docs things to fix when you get a change:
- [x] On Getting started with Empirical development under One-time preparation, the first item is supposed to list dependencies for different OSes but it doesn't.
- [x] Typo in step 3 of One-time preparation (Epirical rather than Empirical)
- [x] Front page - I don't think there are supposed to be that many things called "Indices and tables"

**Comment by bocajnotnef** [comment]
- [ ] update authors list
 - [ ] test (or have someone test) docs for adding tests/documentation
 - [ ] begin changing source comments to get pulled into doxygen XML
 - [ ] Update the readme on the github page...?

**Comment by bocajnotnef** [comment]
- [ ] Make a note for people who have contributor access to the github repo that they don't have to fork & add upstream target

**Comment by bocajnotnef** [comment]
- [ ] `make install-dependencies` should cover most of the one-time prep stuff

dependencies needed to install on clean debian system:
 * cmake
 * g++
 * flex
 * bison
 * python-virtualenv


* need to enable multi/universe in package manager (debian)

**Comment by bocajnotnef** [comment]
- [ ] Doxygen ignores nearly all of BitSet.h--likely has something to do with odd macro expansion, ref. http://www.stack.nl/~dimitri/doxygen/manual/preprocessing.html

**Comment by emilydolson** [comment]
- [ ] Clarify that make install-dependencies handles creating the virtual environment. (also that you might need to run it with sudo, but maybe that was just something weird about my setup)

**Comment by bocajnotnef** [comment]
`make install-dependencies` should not require sudo.... Concerning that it would.

**Comment by emilydolson** [comment]
FYI: the sudo thing was a bug with my system Python configuration.

There are probably some improvements that could still be made to make install-dependencies, but other wise I think the last pieces of this are fixed in https://github.com/devosoft/Empirical/pull/140
