### ISSUE TITLE
Make generic EMP_EVO_FORWARD 

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#74]
We have versions of EMP_EVO_FORWARD that forward to one object or to two objects. It would be nice if we had a generic that would figure out how many objects it was given and call the appropriate version.

It would be really nice if it would automatically figure out which managers the forwarded function could be called on, but that would be more challenging.

**Comment by mercere99** [comment]
Given that the new emp::World doesn't require any kind of forwarding, I'm going to close this issue.
