### ISSUE TITLE
Doxygen Installation Notes

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#9]
I'm gonna ssume we'll only be running Doxygen in a dev environment, so these'll be considered dev dependencies:

From [the install docs](http://www.stack.nl/~dimitri/doxygen/manual/install.html):
- flex
- bison
- libiconv
- make
- strip

**Comment by bocajnotnef** [comment]
It's also recommended to have `graphviz`, a QT toolkit and LaTEX

**Comment by bocajnotnef** [comment]
Pulling install source from: ftp://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.src.tar.gz

**Comment by bocajnotnef** [comment]
Breathe dependency:
 * pypi (and thusly python)

**Comment by bocajnotnef** [comment]
Reminds me, new thing to do:
 - [ ] document python virtual environments

**Comment by bocajnotnef** [comment]
Right, so: doxygen and breathe are stashed in third-party now; will probably later remove them from there and have them downloaded/extracted via a maketarget to slim down our project size, but for now they can sit there.

Sphinx is installed via pypi into a virtualenvironment; since virtualenvs don't move well (absolute paths, huzzah) and cross-system things are an issue I've gitignored the env I used (thirdparty/env) and will instead document how to set up a virtualenv to install sphinx. If this isn't a good solution then I can look into downloading sphinx source into third-party with everything else. 

(currently I don't like how we have some things pypi'd and some things third-party'd, but I'm not sure there's currently a better plan)

**Comment by bocajnotnef** [comment]
Currently docing virtualenvs here since there isn't a more formal place to do so.

And by docing I mean linking to other docs: http://docs.python-guide.org/en/latest/dev/virtualenvs/

Basically, install the virtualenv python packages so that other python packages can be installed in a sandbox that won't contaminate the rest of your system.

so:
```
$ pwd
/home/bocajnotnef/git/Empirical/third-party
$ python -m virtualenv env
[env stuff]
$ source env/bin/activate
(env) $ pip install sphinx
[install stuff]
(env) $ cd ../doc/
(env) $ make html
```

behold the glorious docs

**Comment by bocajnotnef** [comment]
Alright, slight issue here: I can doc how to get dependencies installed on a *nix system just fine but I don't have access to an OSX box to figure out how to get things running there.

**Comment by mercere99** [comment]
@emilydolson - is everything solid with Doxygen now?  Should we re-close this ticket (possibly in conjunction with opening a new one with the current set of issues?)

**Comment by emilydolson** [comment]
I really want to run through a clean install on each of Linux, mac, and Windows before I say that the current scripts are 100% ready to hand to potential new contributors.

**Comment by bocajnotnef** [comment]
Doing a clean install would also be good to make sure all the project
requirements are installed as well--beyond just doxygen.

**Comment by emilydolson** [comment]
Okay, I've run through many clean installs over the past two years without issues, so I'm going to actually close this now
