### ISSUE TITLE
Weird error when constructing random number generator and world

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#91]
Building a random number generator (emp::Random) without passing it an argument (i.e. letting it use the default) and then passing that random number generator into a world constructor throws a weird type error.

**Comment by mercere99** [comment]
I can't reproduce this error... can you give example code?  Take a look in examples/evo/ where some of the examples are done this way (such as World.cc).

**Comment by emilydolson** [comment]
It was on Sarah's computer. I'll see if I can reproduce it on mine tomorrow.

**Comment by mercere99** [comment]
@emilydolson Have you been able to reproduce this error?  If not my inclination is to close this issue.
